### ISSUE TITLE
Hoorn 6951 not in charter company

### ISSUE THREAD

**Issue by slamchan** [Victorum-Universalis-VU/Victorum-Universalis#10]
Description: Hoorn (6951) is not in charter company (Dutch Charter)

Version: Latest dev branch (EU4 v1.31.5.2 (eb36))

![image](https://user-images.githubusercontent.com/43639359/126013173-04c6da92-e7d5-48c2-8d8a-47fedfef8521.png)

**Comment by letole** [comment]
Fixed
