### ISSUE TITLE
Incident Holstein

### ISSUE THREAD

**Issue by letole** [Victorum-Universalis-VU/Victorum-Universalis#18]
With the imperial Incident "The Question of Holstein" if the Emperor relinquishes the claims, only the province itself is removed from the empire. Well, the incident is about Holstein staying part of the empire and the emperor fighting Denmark for it (unless Denmark gives it up), or Holstein no longer being part of the Empire. Holstein in this case being the Dukedom of Holstein. Not really a bug, but more code needing to be changed as in base game, only the province of Holstein is part of the empire.

by Ishmael on discord

**Comment by AkiraBlaze** [comment]
This should now be fixed as per an update to the incident event, please monitor!
