### ISSUE TITLE
burgundy

### ISSUE THREAD

**Issue by letole** [Victorum-Universalis-VU/Victorum-Universalis#19]
part 1:

Also not so much a bug but under the AI flanders starts with 50% liberty desire towards burgundy, a human burgundy can sort it no issue but every game i've played so far has seen Flanders have it's independence supported and Burgandy fall apart before too long due to Flanders allying with other PU's

A suggestion might be to move the "Burgundian Hegemony" triggered modifier that gives it the relations slots to deal with it's PU's to and estate edict (like the British Strong Marches for England) that would also lower liberty desire by a small amount, or add an AI only modifier to burgundy that lowers the liberty desire of it's subjects.

part 2:

Artois should probably be a PU of burgundy at the start

by Akira Blaze on discord

**Comment by AkiraBlaze** [comment]
I resolved this with one of my commits earlier, artois is now a PU and burgandy has it's correct vassals, along with the modifier to support them :)
