### ISSUE TITLE
naval bases

### ISSUE THREAD

**Issue by letole** [Victorum-Universalis-VU/Victorum-Universalis#40]
Currently naval bases are very overpowered, especially with how many there are in the mod now. Luxi, Azura Blaze, and me had a discussion about this on discord and came to the conclusion that the best course of action would be to remove the naval force limit from the naval base (there are buildings for that) and have a tiered system of naval bases, upgradable via descision. this is a pretly long coding project.

**Comment by AkiraBlaze** [comment]
if someone can suggest me the modifiers and potential pricing/requirements I can look into this :)

**Comment by letole** [comment]
I would suggest 4 tiers, tier 0-3.
tier 0: 
natural naval base:
local ship repair +5%
In all provinces with potential for a naval base

tier 1:
small naval base:
local ship recruit cost and time -5%
local ship repair +10%
upgrade cost 0>1 = 200
needs dock

tier 2:
medium naval base
local ship recruit cost and time -10%
local ship repair +15%
upgrade cost 1>2 = 500
needs dock and shipyard

tier 3:
large  naval base:
local ship recruit cost and time -20%
local ship repair +25%
local dev cost -5%
upgrade cost 2>3= 1500
needs drydock and grand shipyard.

**Comment by slamchan** [comment]
AkiraBlaze has done this
